apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-app
  namespace: pdf-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-app
  template:
    metadata:
      labels:
        app: mlops-app
    spec:
      containers:
        - name: mlops-app
          image: your_ecr_image_uri
          ports:
            - containerPort: 8080
